### ISSUE TITLE
webpack compile error

### ISSUE THREAD

**Issue by vimniky** [chenjiahan/rodal#8]
node_modules/rodal/lib/rodal.css:2
.rodal, .rodal-mask {
^

SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/vimniky/Desktop/start-kit2/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/vimniky/Desktop/start-kit2/node_modules/rodal/lib/rodal.js:15:1)
    at Module._compile (module.js:413:34)

**Comment by chenjiahan** [comment]
Please use css-loader && style-loader to pack css files.

**Comment by vimniky** [comment]
Yet ! I'am using css-loader && style-loader . Does rodal support server-rendering ?

**Comment by vimniky** [comment]
Seems rodal can't be use on server side . Here's the problem , require('****.css') would broken on server side .
<img width="665" alt="screen shot 2016-06-14 at 6 28 01 pm" src="https://cloud.githubusercontent.com/assets/11426875/16039736/15ac6c04-325e-11e6-9b3e-0d5bc7571773.png">

**Comment by vimniky** [comment]
I think it can be fix by conditional requiring in rodal.css .

**Comment by chenjiahan** [comment]
@vimniky  Sorry for the late reply, I have fixed this problem and you can manually require rodal.css in v1.3.2.
